// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wMVTCPX19GzxjA22wkaqtX5l77uZ-jQ',
    appId: '1:935335570939:web:c1bb355d8997d9d322ef5e',
    messagingSenderId: '935335570939',
    projectId: 'teachersapp-97f59',
    authDomain: 'teachersapp-97f59.firebaseapp.com',
    storageBucket: 'teachersapp-97f59.appspot.com',
    measurementId: 'G-QHE19CCTXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwIxM24BtRVQ_E1Ni8XZdg-uuQFrN2E8',
    appId: '1:935335570939:android:06ef327fdcb24f3322ef5e',
    messagingSenderId: '935335570939',
    projectId: 'teachersapp-97f59',
    storageBucket: 'teachersapp-97f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fxpy06j77w-PrixRyWb8SWfFbtBuO9I',
    appId: '1:935335570939:ios:639cc34731c0e81d22ef5e',
    messagingSenderId: '935335570939',
    projectId: 'teachersapp-97f59',
    storageBucket: 'teachersapp-97f59.appspot.com',
    iosBundleId: 'com.example.teachersapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7fxpy06j77w-PrixRyWb8SWfFbtBuO9I',
    appId: '1:935335570939:ios:639cc34731c0e81d22ef5e',
    messagingSenderId: '935335570939',
    projectId: 'teachersapp-97f59',
    storageBucket: 'teachersapp-97f59.appspot.com',
    iosBundleId: 'com.example.teachersapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2wMVTCPX19GzxjA22wkaqtX5l77uZ-jQ',
    appId: '1:935335570939:web:003a90b1595499dd22ef5e',
    messagingSenderId: '935335570939',
    projectId: 'teachersapp-97f59',
    authDomain: 'teachersapp-97f59.firebaseapp.com',
    storageBucket: 'teachersapp-97f59.appspot.com',
    measurementId: 'G-B0KPJH5S6E',
  );
}
